"""Create wallet model

Revision ID: f4e4af1d3af2
Revises: f6c26bc714ed
Create Date: 2024-03-19 20:37:59.847054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4e4af1d3af2'
down_revision: Union[str, None] = 'f6c26bc714ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('euro', sa.Integer(), server_default='0', nullable=False),
    sa.Column('dollar', sa.Integer(), server_default='0', nullable=False),
    sa.Column('bitcoin', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ton', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallets')
    # ### end Alembic commands ###
