"""Create card_skill_association model

Revision ID: fca43733bb2d
Revises: 71f57acc5657
Create Date: 2024-03-19 12:13:42.705927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fca43733bb2d'
down_revision: Union[str, None] = '71f57acc5657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_skill_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'skill_id', name='idx_unique_card_skill')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_skill_association')
    # ### end Alembic commands ###
